{% set name = "smina" %}
{% set version = "2021.12.09" %}
{% set commit = "7369fc07394663d8834e13e4e8c02c91af4287ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/jaimergp/smina/archive/{{ version }}.tar.gz
    sha256: 4fdb9a3d0293ceb868b1c492b8e6fb1673948638ccd382174c41e68a443aa795
    patches:
      - cmake.patch
      - MinimizationQuery.cpp.patch

build:
  number: 0
  script:
    - env GIT_HASH={{ commit }} bash {{ RECIPE_DIR }}/build_smina.sh    # [unix]
    - set GIT_HASH={{ commit }}  &&  {{ RECIPE_DIR }}\build_smina.bat   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make     # [unix]
    - ninja    # [win]
  host:
    # Smina not compatible with more recent libboost versions
    # see https://github.com/conda-forge/smina-feedstock/pull/3
    # and https://github.com/conda-forge/smina-feedstock/pull/4
    - libboost-devel 1.82.*
    - eigen
    - openbabel
  run:
    - openbabel

test:
  commands:
    - smina --help
    - smina --version

about:
  home: https://sourceforge.net/projects/smina/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.APACHE
  summary: 'A fork of AutoDock Vina that is customized to better support scoring function development and high-performance energy minimization'
  description: |
    A fork of AutoDock Vina that is customized to better support scoring
    function development and high-performance energy minimization. smina
    is maintained by David Koes at the University of Pittsburgh and
    is not directly affiliated with the AutoDock project.
  doc_url: https://sourceforge.net/p/smina/discussion/
  dev_url: https://sourceforge.net/p/smina/code/ci/master/tree/

extra:
  recipe-maintainers:
    - jaimergp
